export const TODOS_FETCH_START = 'TODOS_FETCH_START';
export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODOS_FETCH_ERROR = 'TODOS_FETCH_ERROR';

export const TODOS_CHANGE_DONE_START = 'TODOS_CHANGE_DONE_START';
export const TODOS_CHANGE_DONE_SUCCESS = 'TODOS_CHANGE_DONE_SUCCESS';
export const TODOS_CHANGE_DONE_ERROR = 'TODOS_CHANGE_DONE_ERROR';

export const TODOS_DELETE_START = 'TODOS_DELETE_START';
export const TODOS_DELETE_SUCCESS = 'TODOS_DELETE_SUCCESS';
export const TODOS_DELETE_ERROR = 'TODOS_DELETE_ERROR';
