export const TODOS_FETCH_START = 'TODOS_FETCH_START';
export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODOS_FETCH_ERROR = 'TODOS_FETCH_ERROR';

export const TODOS_CHANGE_DONE_START = 'TODOS_CHANGE_DONE_START';
export const TODOS_CHANGE_DONE_SUCCESS = 'TODOS_CHANGE_DONE_SUCCESS';
export const TODOS_CHANGE_DONE_ERROR = 'TODOS_CHANGE_DONE_ERROR';
